language: ruby
rvm:
  - 2.4.3
before_install:
  - gem update --system
  - gem install bundler
before_script:
  - psql -c 'create database shim_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:migrate --trace

