source 'https://rubygems.org'

# Declare your gem's dependencies in canvas_shim.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

gem 'actioncable', '~> 5'
gem 'actionmailer', '~> 5'
gem 'actionpack', '~> 5'
gem 'actionview', '~> 5'
gem 'activejob', '~> 5'
gem 'activemodel', '~> 5'
gem 'activerecord', '~> 5'
gem 'activesupport', '~> 5'
gem 'addressable', '~> 2'
gem 'arel', '~> 7'
gem 'aws-eventstream', '~> 1'
gem 'aws-partitions', '~> 1'
gem 'aws-sdk-core', '~> 3'
gem 'aws-sdk-dynamodb', '~> 1'
gem 'aws-sdk-kms', '~> 1'
gem 'aws-sdk-s3', '~> 1'
gem 'aws-sdk-secretsmanager', '~> 1'
gem 'aws-sdk-sqs', '~> 1'
gem 'aws-sigv4', '~> 1'
gem 'axiom-types', '~> 0'
gem 'better_errors', '~> 2'
gem 'binding_of_caller', '~> 0'
gem 'builder', '~> 3'
gem 'bundler', '~> 2'
gem 'business', '~> 1'
gem 'chronic', '~> 0.10'
gem 'coderay', '~> 1'
gem 'coercible', '~> 1'
gem 'coffee-rails', '~> 4'
gem 'coffee-script', '~> 2'
gem 'coffee-script-source', '~> 1'
gem 'concurrent-ruby', '~> 1'
gem 'crack', '~> 0'
gem 'crass', '~> 1'
gem 'debug_inspector', '~> 0'
gem 'decorators', '~> 2'
gem 'delayed_job', '~> 4'
gem 'delayed_job_active_record', '~> 4'
gem 'descendants_tracker', '~> 0'
gem 'diff-lcs', '~> 1'
gem 'dotenv', '~> 2'
gem 'equalizer', '~> 0'
gem 'erubi', '~> 1'
gem 'erubis', '~> 2'
gem 'ethon', '~> 0'
gem 'execjs', '~> 2'
gem 'faraday', '~> 0'
gem 'ffi', '~> 1'
gem 'footrest', '~> 0'
gem 'globalid', '~> 0'
gem 'groupdate', '~> 4'
gem 'hashdiff', '~> 0'
gem 'httparty', '~> 0'
gem 'i18n', '~> 1'
gem 'ice_nine', '~> 0'
gem 'inflecto', '~> 0'
gem 'jmespath', '~> 1'
gem 'json', '~> 2'
gem 'link_header', '~> 0'
gem 'loofah', '~> 2'
gem 'mail', '~> 2'
gem 'method_source', '~> 0'
gem 'mime-types', '~> 3'
gem 'mime-types-data', '~> 3'
gem 'mini_mime', '~> 1'
gem 'mini_portile2', '~> 2'
gem 'minitest', '~> 5'
gem 'multi_xml', '~> 0'
gem 'multipart-post', '~> 2'
gem 'nio4r', '~> 2'
gem 'nokogiri', '~> 1'
gem 'pandarus', '~> 0'
gem 'pg', '~> 1'
gem 'pipeline_publisher_ruby', '~> 1'
gem 'pry', '~> 0'
gem 'pry-rails', '~> 0'
gem 'public_suffix', '~> 3'
gem 'rack', '~> 2'
gem 'rack-test', '~> 0'
gem 'rails', '~> 5.0.7.2'
gem 'rails-dom-testing', '~> 2'
gem 'rails-html-sanitizer', '~> 1'
gem 'railties', '~> 5'
gem 'rake', '~> 12'
gem 'sass', '~> 3'
gem 'sass-listen', '~> 4'
gem 'sass-rails', '~> 5'
gem 'sprockets', '~> 3'
gem 'sprockets-rails', '~> 3'
gem 'rb-fsevent', '~> 0'
gem 'rspec-core', '~> 3'
gem 'rspec-expectations', '~> 3'
gem 'rspec-mocks', '~> 3'
gem 'rspec-support', '~> 3'
gem 'thor', '~> 0'
gem 'thread_safe', '~> 0'
gem 'tilt', '~> 2'
gem 'typhoeus', '~> 1'
gem 'tzinfo', '~> 1'
gem 'uglifier', '~> 4'
gem 'virtus', '~> 1'
gem 'websocket-driver', '~> 0'
gem 'websocket-extensions', '~> 0'



group :test do
  gem 'webmock'
end

group :development, :test do
  gem 'byebug', groups: ['development', 'test']
  gem 'dotenv-rails'
  gem 'faker'
  gem 'pry-byebug'
  gem 'rspec-rails', '~> 3'
  gem 'spring'
  gem 'awesome_print'
  gem 'timecop'
  gem 'vcr'
  gem 'sentry-raven'
end
