# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "rspec"
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-18.04
    services:
      postgres:
        image: postgres:9-alpine
        env:
          PG_DATABASE: postgres
          PG_HOST: localhost
          PG_PORT: 5432
          PG_USER: postgres
          RAILS_ENV: test
        # needed because the postgres container does not provide a healthcheck
        # tmpfs makes DB faster by using RAM
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.4.10
          bundler-cache: true
      - name: Run bundler
        run: bundle install --path vendor/bundle
      - name: Setup DB, Run tests
        env:
          PG_HOST: localhost
          PG_USER: postgres
          PG_PASSWORD: postgres
          PG_PORT: ${{ job.services.postgres.ports[5432] }}
          RAILS_ENV: test
        run: |
          sudo apt-get -yqq install libpq-dev
          bin/rails db:create db:migrate
          bundle exec rspec
